### ISSUE TITLE
Can not install Figma font on Ubuntu

### ISSUE THREAD

**Issue by LBhelena** [302bis/figma-app-ubuntu#2]
Hi :),

I have a issue when i create a new file and add text layer. The issue is the text not show on file although layer exist.

I try to enable font but i see a warning message:
"Local fonts are currently not supported for this operating system."

How can i fix it on Ubuntu?

Thanks

**Comment by 302bis** [comment]
Hi Helena! thanks for use build that I made. Unfortunately, in this case, you will not be able to use the operating system fonts because this build was created with *Electron* which means it is a wrapper of the web version.

This is an unofficial version of the application. When an official version comes out, surely, you can you can use the operating system fonts.

On the other hand, I have to use, google web font, which --at the end of the day-- is not so bad.

Kindly regards, Patricio.
